[package]
name = "hyperip"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
powershell_script = "1.1.0"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
